import type { Transaction } from "./types"

export const transactions: Transaction[] = [
  {
    id: "1",
    date: "2024-07-26",
    description: "Apple Store",
    amount: -599.99,
    status: "pending",
    category: "Shopping",
  },
  {
    id: "2",
    date: "2024-07-25",
    description: "Monthly Salary",
    amount: 5000,
    status: "posted",
    category: "Income",
  },
  {
    id: "3",
    date: "2024-07-24",
    description: "Starbucks",
    amount: -5.75,
    status: "posted",
    category: "Food",
  },
  {
    id: "4",
    date: "2024-07-23",
    description: "Gas Station",
    amount: -45.2,
    status: "posted",
    category: "Gas",
  },
  {
    id: "5",
    date: "2024-07-22",
    description: "Netflix Subscription",
    amount: -15.49,
    status: "posted",
    category: "Subscription",
  },
  {
    id: "6",
    date: "2024-07-21",
    description: "Grocery Shopping",
    amount: -124.5,
    status: "posted",
    category: "Groceries",
  },
  {
    id: "7",
    date: "2024-07-20",
    description: "Electricity Bill",
    amount: -75.0,
    status: "posted",
    category: "Utilities",
  },
  {
    id: "8",
    date: "2024-07-19",
    description: "Cinema Tickets",
    amount: -30.0,
    status: "posted",
    category: "Entertainment",
  },
  {
    id: "9",
    date: "2024-07-18",
    description: "Uber Ride",
    amount: -18.9,
    status: "posted",
    category: "Transport",
  },
  {
    id: "10",
    date: "2024-07-17",
    description: "Zara",
    amount: -250.0,
    status: "pending",
    category: "Shopping",
  },
]
